### PR TITLE
Fix use-package integration when use-package is not loaded at runtime

### PR DESCRIPTION
**Pull request by PythonNut**
If `use-package` is never loaded, the `(with-eval-after-load 'use-package ...)` body never runs. To avoid this, I define the functions required by the compiled output of `use-package` unconditionally. The rest of the integration remains in the `(with-eval-after-load ...)` as before.

### CODE REVIEW

**Comment by raxod502** [comment]
This makes sense. We want to merge into `develop`, though, not `master`.

**Comment by raxod502** [comment]
Wow, I didn't actually know you could do that without opening a new pull request.

**Comment by raxod502** [comment]
In general we like commit messages that are 50 characters or less, see https://chris.beams.io/posts/git-commit/.

**Comment by PythonNut** [comment]
@raxod502 what would you have suggested then?

**Comment by raxod502** [comment]
How about:

```
Don't require use-package to be loaded at runtime

If use-package is never loaded, the (with-eval-after-load 'use-package
...) body never runs. To avoid this, I define the functions required
by the compiled output of use-package unconditionally. The rest of the
integration remains in the (with-eval-after-load ...) as before.
```

In general, I think it's unnecessary to capture all the important information in the subject line. That's what the body is for.

**Pull request merged**
