### PR TITLE
Add custom variables for additional forges

### PR DESCRIPTION
**Pull request by snan**
I host a bunch of forks (and own packages) at another forge so I made this customizable in straight. ♥

### CODE REVIEW

**Comment by snan** [comment]
I'll look into the failing tests!

**Comment by snan** [comment]
Docker? That doesn't seem related to the patch…?

**Comment by snan** [comment]
Jolly good!

**Review by progfolio — CHANGES_REQUESTED** [review]
Instead of having multiple variables, I'd rather have the information stored together. Roughly, something like the following:

```emacs-lisp
(defcustom straight-hosts '((github    "github.com"    ".git")
                            (gitlab    "gitlab.com"    ".git")
                            (bitbucket "bitbucket.com" ".git"))
  "Alist containing URI information for hosted forges.
Each element is of the form: (HOST DOMAIN REPO-SUFFIX).
HOST is a unique symbol meant to be used with the :host recipe keyword.
DOMAIN is a string representing the domain and top-level domain.
REPO-SUFFIX is appended to the repository name in the URI.")
```

Given a key, the domain and repo suffix can be retrieved all at once.

**Comment by snan** [comment]
Good idea, thank you. I [removed the verical alignment](https://idiomdrottning.org/lisp-whitespace).

**Review by progfolio — APPROVED** [review]

**Comment by progfolio** [comment]
> Good idea, thank you.

You're welcome. Thank you for the pull request.

> I removed the vertical alignment.

I can't say I'm convinced by this. It lays out an argument without doing much to substantiate it.
It might be more convincing if it provided concrete examples with each claim.
In any case, we don't have any requirements regarding vertical alignment, so your change is fine by me.


Thanks again.

**Comment by snan** [comment]
> It might be more convincing if it provided concrete examples with each claim.

That is very good feedback, thank you!

**Pull request merged**
