### PR TITLE
straight--run-build-commands: error on failed :pre/post-build command

### PR DESCRIPTION
**Pull request by progfolio**
Prefer errors over warnings for command failure.
Previous behavior would allow package :pre/post-build to fail and be silently
ignored on restarts.

Now if a `:pre/post-build` error occurs the user is presented with the `*Warnings*` buffer (which details the error and the recipe in which it occurred) and, in the case of a shell command error, the `*straight-process-buffer*` on start.

### CODE REVIEW

**Comment by progfolio** [comment]
e.g.

**Review by raxod502 — COMMENTED** [review]
This seems like it should work, but perhaps we would be able to facilitate greater code reuse if we were to use `straight--get-call` instead of `straight--check-call`, because `straight--get-call` will already throw an error and display the process buffer when the command fails. Then all we would have to do here is (optionally) re-throw the error with some more explanation in the description. What do you think?

**Comment by progfolio** [comment]
`straight--get-call` throws the error, but it does not display the `straight-process-buffer` when an error is thrown.  Would prefer a patch similar to #573 for `straight--get-call` as well?

**Comment by raxod502** [comment]
Oh, I didn't realize that. I guess it is up to you what you think would be more elegant. I don't have a strong opinion. It would be nice as a concept for any command errors to pop open the buffer in the same way, but on the other hand it's possible that in some circumstance maybe we do not want to pop open the buffer on an error.

**Comment by progfolio** [comment]
> It would be nice as a concept for any command errors to pop open the buffer in the same way, but on the other hand it's possible that in some circumstance maybe we do not want to pop open the buffer on an error.

Agreed. I haven't thought of a clean interface to allow this just yet, but I have it on my TODO list.
I'm going to merge this as is so we get the benefit of catching the errors. I have it in my notes to clean this up once the above is addressed.

**Pull request merged**
