### PR TITLE
Fixes for the latest native-compile-async API

### PR DESCRIPTION
**Pull request by flatwhatson**
A recent change on the `native-comp` branch has meant that passing load flag `late` is equivalent to passing load flag `t`, which causes packages to be unconditionally loaded after they're compiled.  This leads to all sorts of problems as some Elisp packages will error instantly on load!

~~This patch simply removes the `load` flag which should give the desired behaviour.~~

Edit: After discussion with upstream, we've agreed on an API, this PR implements the necessary changes.

### CODE REVIEW

**Comment by progfolio** [comment]
Thank you for the pull. Just to make sure I understand correctly, this is due to the changes here?:

https://github.com/emacs-mirror/emacs/commit/6781cd670d1487bbf0364d80de68ca9733342769#diff-33e02a4d29a78e1ab21694eaba92b1b59839106ffb711326a7b7e344a4706b07

**Comment by flatwhatson** [comment]
Yes that's correct.

**Comment by flatwhatson** [comment]
FYI this change also breaks our usage of `comp-deferred-compilation-black-list` to prevent compilation of `no-native-compile` packages, because that list is only checked when compilation is requested with the `late` flag.

**Comment by flatwhatson** [comment]
I've opened a ticket upstream to discuss this issue: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44813

**Comment by flatwhatson** [comment]
Ok, Andrea has kindly implemented the necessary changes to support straight's use-case upstream.  I've updated this patch with the necessary changes on our side.

The only possible problem I can see is that this is a hard API break; older builds of native-comp will no longer be supported.  Personally I think this is fine, but it should at least be mentioned.  I've added a warning note in the commit message.

**Comment by progfolio** [comment]
CI failure due to:
```
Warning (emacs): 
straight.el:4748: White space found at end of line
```

**Review by progfolio — APPROVED** [review]
I don't use the native-comp branch just yet, but I read through your previous contributions and the latest patch to the API and everything looks good to me. We could `define-obsolete-variable-alias` for the symbol name change, but I don't think it's necessarily a blocker. As you've mentioned before this is a change that will affect a limited number of users (on our develop branch and on the native-comp branch of Emacs)

@raxod502: thoughts?

**Review by progfolio — APPROVED** [review]

**Comment by flatwhatson** [comment]
Sorry for the fresh push, the previous version had a silly bug in `straight--native-compile-file-p`.

**Comment by progfolio** [comment]
Not a problem. Just inverted logic for the predicate, correct?

**Comment by flatwhatson** [comment]
Yeah.  Not sure how I missed that the first time through testing.  Whoops!

**Review by raxod502 — APPROVED** [review]
If it's a change in the variable name upstream, I don't think it's sensible to try adding an alias here in `straight.el`. Might be worth adding one upstream, depending on what the policy is there. I have no strong thoughts. I like the name change though, always good to be more inclusive.

**Comment by progfolio** [comment]
Thank you, @flatwhatson.

**Pull request merged**
